In [1]:
import tensorflow as tf

In [2]:
# Check tensorflow version
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [3]:
# Creating Tensors
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [4]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>

In [5]:
number

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>

In [6]:
floating

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>

In [7]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [8]:
rank1_tensor

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>

In [9]:
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>

In [10]:
# To determine the rank
tf.rank(rank2_tensor)

<tf.Tensor: id=42, shape=(), dtype=int32, numpy=2>

In [11]:
# get the shape
rank2_tensor.shape

TensorShape([2, 2])

In [12]:
# changing Shape
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones

In [13]:
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]

In [14]:
tensor3 = tf.reshape(tensor2, [3,-1])  # -1 tells the tensor to calculate the size of the dimension in that place

In [15]:
tensor1

<tf.Tensor: id=45, shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [16]:
tensor2

<tf.Tensor: id=47, shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [17]:
tensor3

<tf.Tensor: id=49, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

In [19]:
tensor = tf.Variable(matrix, dtype=tf.int32) 

In [20]:
tensor

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>

In [21]:
tf.rank(tensor)

<tf.Tensor: id=59, shape=(), dtype=int32, numpy=2>

In [22]:
tensor.shape

TensorShape([4, 5])

In [23]:
three = tensor[0,2]  # selects the 3rd element from the 1st row

In [24]:
print(three)

tf.Tensor(3, shape=(), dtype=int32)


In [25]:
row1 = tensor[0]  # selects the first row

In [26]:
row1

<tf.Tensor: id=69, shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [27]:
column1 = tensor[:, 0]  # selects the first column

In [28]:
column1

<tf.Tensor: id=74, shape=(4,), dtype=int32, numpy=array([ 1,  6, 11, 16], dtype=int32)>

In [29]:
row_2_and_4 = tensor[1::2]  # selects second and fourth row

In [30]:
row_2_and_4

<tf.Tensor: id=79, shape=(2, 5), dtype=int32, numpy=
array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]], dtype=int32)>

In [31]:
column_1_in_row_2_and_3 = tensor[1:3, 0]

In [32]:
with tf.Session() as sess:
    tensor.eval()

AttributeError: module 'tensorflow' has no attribute 'Session'